/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Ponto;
import model.Quadrante;

/**
 *
 * @author helenas
 */
public class AppQuestao02 extends javax.swing.JFrame {

    /**
     * Creates new form AppQuestao02
     */
    public AppQuestao02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eixoX = new javax.swing.JLabel();
        eixoY = new javax.swing.JLabel();
        tfEixoX = new javax.swing.JTextField();
        tfEixoY = new javax.swing.JTextField();
        btVerificar = new javax.swing.JButton();
        cbEixoX = new javax.swing.JCheckBox();
        cbEixoY = new javax.swing.JCheckBox();
        cbQuad1 = new javax.swing.JCheckBox();
        cbQuad2 = new javax.swing.JCheckBox();
        cbQuad3 = new javax.swing.JCheckBox();
        posicao = new javax.swing.JLabel();
        cbQuad4 = new javax.swing.JCheckBox();
        cbQuadNenhum = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eixoX.setText("Eixo X");

        eixoY.setText("Eixo Y");

        tfEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEixoXActionPerformed(evt);
            }
        });

        btVerificar.setText("Verificar");
        btVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        cbEixoX.setText("Incide sobre o eixo X");
        cbEixoX.setEnabled(false);
        cbEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEixoXActionPerformed(evt);
            }
        });

        cbEixoY.setText("Incide sobre o eixo Y");
        cbEixoY.setEnabled(false);

        cbQuad1.setText("Quadrante 1");
        cbQuad1.setEnabled(false);

        cbQuad2.setText("Quadrante 2");
        cbQuad2.setEnabled(false);

        cbQuad3.setText("Quadrante 3");
        cbQuad3.setEnabled(false);

        posicao.setText("Posição");

        cbQuad4.setText("Quadrante 4");
        cbQuad4.setEnabled(false);

        cbQuadNenhum.setText("Nenhum ");
        cbQuadNenhum.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbQuadNenhum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicao)
                            .addComponent(cbEixoX)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbQuad1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEixoY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbQuad4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbQuad3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbQuad2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eixoY)
                            .addComponent(eixoX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVerificar)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eixoX)
                            .addComponent(tfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eixoY)
                            .addComponent(tfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btVerificar)))
                .addGap(19, 19, 19)
                .addComponent(posicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuad3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuad4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuadNenhum)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEixoXActionPerformed

    private void onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClick
        int x = Integer.parseInt(tfEixoX.getText());
        int y = Integer.parseInt(tfEixoY.getText());

        Ponto meuPonto = new Ponto(x, y);

        cbEixoX.setSelected(meuPonto.estaIncidindoSobreX());
        cbEixoY.setSelected(meuPonto.estaIncidindoSobreY());
        cbQuad1.setSelected(meuPonto.identificarQuadrante() == Quadrante.PRIMEIRO);
        cbQuad2.setSelected(meuPonto.identificarQuadrante() == Quadrante.SEGUNDO);
        cbQuad3.setSelected(meuPonto.identificarQuadrante() == Quadrante.TERCEIRO);
        cbQuad4.setSelected(meuPonto.identificarQuadrante() == Quadrante.QUARTO);
        cbQuadNenhum.setSelected(meuPonto.identificarQuadrante() == Quadrante.NENHUM);

    }//GEN-LAST:event_onClick

    private void cbEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEixoXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppQuestao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppQuestao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppQuestao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppQuestao02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppQuestao02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerificar;
    private javax.swing.JCheckBox cbEixoX;
    private javax.swing.JCheckBox cbEixoY;
    private javax.swing.JCheckBox cbQuad1;
    private javax.swing.JCheckBox cbQuad2;
    private javax.swing.JCheckBox cbQuad3;
    private javax.swing.JCheckBox cbQuad4;
    private javax.swing.JCheckBox cbQuadNenhum;
    private javax.swing.JLabel eixoX;
    private javax.swing.JLabel eixoY;
    private javax.swing.JLabel posicao;
    private javax.swing.JTextField tfEixoX;
    private javax.swing.JTextField tfEixoY;
    // End of variables declaration//GEN-END:variables
}
